### ISSUE TITLE
Hostile Mobs Stay Hostile

### ISSUE THREAD

**Issue by Psychonator17** [iChun/Morph#1076]
So, I've started using the Morph Mod on 12.2, and it's a lot of fun (Can't wait for more abilities to be added). There's just one issue I have: hostile mobs aren't supposed to attack you when you've morphed into one of them, but every single hostile mob attacks me anyway. I've used every different hostile ability mode, I changed the distance check, tried everything I could do with the mod, and they STILL attack me!

Is anyone else having this issue? Could it be because another mod I have is conflicting with hostile abilities? I could really use some help here.

**Comment by ClaraOswald666** [comment]
Same here!!

**Comment by CritFlaw** [comment]
Same here, though I've only tried hostile mode 5, and am only now trying a negative distance check. Seems like this feature has yet to be implemented...

**Comment by CritFlaw** [comment]
Negative distance check doesn't work either.

**Comment by iChun** [comment]
Since @CritFlaw asked me on Twitter:

I didn't make abilities for Morph 1.12.2. Someone ported them over for me. I don't currently plan on supporting Morph 1.12.2 any more (especially abilities) so I can't make any promises on the hostile ability getting fixed. 
https://twitter.com/ohaiiChun/status/1264989975226900480


If anyone finds out the issue and submits a PR to fix it I wouldn't mind pulling it in and pushing out an update.

**Comment by CritFlaw** [comment]
Could this someone be given co-authorship abilities so they could port those over/we could see if they have any plans to port them? Is this a difficult feature to implement in 1.12?

I understand you're not interested in supporting the mod in 1.12, but knowing very little of moddev, I was wondering if you had an idea of the work involved.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
