### ISSUE TITLE
Shader color flickering

### ISSUE THREAD

**Issue by Lunasulpix** [iChun/Morph#1085]
I dont exactly know whats causing it but having the morph menu open to pick a morph while playing with a shader (I was playing with Sildurs Vibrant Shaders v1.22 Medium) causes the screen to flicker while looking at certain things in the area.
If anybody knows a fix besides turning off the shader that would be greatly appreciated

[https://youtu.be/tqD96CtVnDU](url)

**Comment by roroB20** [comment]
Yes, I do have the same issue with Morph v1.12.2-7.2.1. 
It only occurs when I'm playing on a 1.12.2 server though, on a local game there is only Morph's GUI flickering instead of the whole screen.

A fix would be greatly appreciable because it's very annoying and epileptic... can even turn the whole screen black when looking at a certain direction, making the mod almost unusable.

PS: I'm using - 1.12.2-forge-14.23.5.2855 
                     - OptiFine_1.12.2_HD_U_G5
                     - ComplementaryShaders_v4.2.2

I hope that could help resolving that issue ! 
Best regards.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
