### ISSUE TITLE
Support for 1.16.X

### ISSUE THREAD

**Issue by Razva** [iChun/Morph#1089]
Would you accept donations for updating this mod to 1.16.X?

**Comment by iChun** [comment]
Sorry, but no. I'd much prefer if donations were made in good grace as thanks for my work, rather than the other way around. The reason that I'm not currently working on porting to 1.16 is not of financial origin. I've outlined a little bit of it in a comment you can find here: https://github.com/iChun/Morph/issues/884#issuecomment-615972544

However, the thought is much appreciated. Thanks so much for the support!

**Comment by Razva** [comment]
Thank you for the prompt answer! Would you mind if somebody would continue developing/updating this?

**Comment by iChun** [comment]
I can't stop anyone from making ports or making their own interpretations,
but I would still very much so like to work on this mod in the future. I
haven't given up this mod just yet. It'll just have to wait till I have
time.
