### ISSUE TITLE
Morph 1.12.2 Mob Abilities

### ISSUE THREAD

**Issue by MSCourier** [iChun/Morph#1129]
Hi! I've recently wanted to start configuring abilities for other mobs from other mods such as bewitchment, and ice and fire. However I cannot seem to get it to work. Here is my file:
https://github.com/MSCourier/Morph/blob/main/AbilitySupport.json

**Comment by BruteTigrex** [comment]
I also tried to do this a year ago and it didn't work for me either.
Of course, I'm not very versed in moding, but I seem to understand what the reason is.
Perhaps this is due to the NBT of dragons.
I have no idea how to fix this, but I hope this helps you. Well, or IChun itself will see and do something

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
