### ISSUE TITLE
Add milestone (labels?) for 1.16 work?

### ISSUE THREAD

**Issue by austinkeller** [iChun/Morph#1147]
I noticed that iChunUtils was recently updated to 1.16 support https://github.com/iChun/iChunUtil/commit/c251e193c5e0743d6ad36a6e4226ef61153f4721

Are open tasks that people could pick up to help porting Morph to 1.16 as well? If so, maybe we could make them discoverable by adding a milestone to the issues in Github?

I tried searching for a thread on what is needed for porting to 1.16 but only have found this so far: https://github.com/iChun/Morph/issues/1089#issuecomment-670929679

**Comment by iChun** [comment]
I understand that you've looked through the iChunUtil repo and the comments on the 1.16 port. 

However, at this point in time, absolutely no work has been put into porting Morph to 1.16 at all. The entire mod loading system needs a rework due to FML changes and the Morph Variants system, although working, needs a bit of a refactor. Abilities also require a refactor, but I have learnt a lot from modding from the past few years.

I plan on hopefully tackling an update for this mod again soon but as other clones exist, I have not held it to such a high priority. 

I also plan on skipping 1.16.5 at the moment as 1.17 has dropped. As the situation develops, I'll see if a back-port is possible or necessary.

But until then, the best that anyone can really do is take the entire 1.12 mod source and port it over to 1.16. It won't be easy, and I likely won't be accepting a PR for it as I need to handle some things for the mod differently.

Hope this answers your question.

**Comment by Betelgeusesupergiant** [comment]
1.16 is mostly trash for mods

**Comment by iChun** [comment]
We still gotta move on anyway. Can't be stuck in the past.

**Comment by iChun** [comment]
Morph has just been released for 1.16.5, Hope this helps!

As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier.
