### ISSUE TITLE
Add setting to enable morphing without killing

### ISSUE THREAD

**Issue by Adtp77** [iChun/Morph#1155]
Hello, my child plays with this mod. I was wondering if a feature could be added to enable morphing into any mob without killing them. My child wants to be able to morph into certain mobs without having to kill them (e.g. dogs). My child is young and I am a bit concerned about her having to kill mobs to morph into them. It is a bit upsetting to her when she has to kill certain mobs just to turn into them. Thank you very much!

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier.

I don't know if this will help but I think you can use the /morph command to get a player to morph into the entity they are looking at. I am not sure if the command is working in the older versions of Morph since I had long since dropped support for it.

Unfortunately I have no plans to implement a way of turning into another entity without killing them, as that was the whole premise of the mod, since a significant proportion of the idea was inspired by another game (PROTOTYPE).
