### ISSUE TITLE
Expected better in the new version...

### ISSUE THREAD

**Issue by fireballkallyn** [iChun/Morph#1162]
In the old version it never used to be complicated. You could just press ~ and the morphs showed up and you could use abilities. In the new version it makes the mod absolute garbage.

**Comment by iChun** [comment]
Do you mind elaborating on which version you're talking about?

**Comment by JoelZBub** [comment]
This issue report is absolute garbage. 
If you choose to make an issue report for anything in the future, include the version of Minecraft, Forge version and the mod version at the *very very least.*
Nothing about this "issue report" is helpful in any way.
The issue tracker is here to report issues so that they can be fixed, not to air your whining complaints with verbal abuse toward the developer. 
Be better about your life.

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.

To add to this: Morph, from it's conception, has barely deviated from what it was originally. [ ] for selectors, ` for favourites, and mobs have abilities. Even in the 1.12, it still follows that basic concept, and that carried on into the 1.16.5 version. You may have mistaken this for another mod, or another mod for this, as other Morph clones also exist.

If you want to give criticism, learn to give more constructive criticism rather than tossing trash (like your opinion) at people. Give descriptions, how it could be better/where it could improve, and watch your language. You'd see people be a lot more willing to help you if you did that. 

Be better...just like the new version
