### ISSUE TITLE
Morph Mod crashing with CQR mobs when opening morph menu

### ISSUE THREAD

**Issue by chobani-yogurt** [iChun/Morph#1181]
If you kill a mob from Chocolate Quest Repoured and attempt to open the Morph menu, the game crashes. I am on 1.12.2, and since morph mod works with other mods, I am assuming this is an issue. It appears the error has something to do with loading the entity into the world when using morph mod, but it simply does not allow me to open the morph menu, it just crashes. 

If this is just simple incompatibility, that's fine, but I want to make sure.
This is the full crash report below:

[crash-2022-02-06_11.38.53-client.txt](https://github.com/iChun/Morph/files/8010606/crash-2022-02-06_11.38.53-client.txt)

**Comment by iChun** [comment]
I looked at the crash and it looks like  it's crashing on the cqr side. Unfortunately I no longer support Morph for 1.12.2 due to its age and its vastly different code base compared to the version available now. You can try reporting with this crash report on the cqr side if they're still maintaining their version.
