### ISSUE TITLE
Skin bug [Morph + SmartMoving] 1.7.10

### ISSUE THREAD

**Issue by rustzz** [iChun/Morph#1182]
I know that the version is no longer supported. but maybe there is a solution to this problem from the community?

lol looks funny
![image](https://user-images.githubusercontent.com/74064444/152764698-19031c71-39e1-4265-b6ec-7806225e5b29.png)
![image](https://user-images.githubusercontent.com/74064444/152764715-6c140bda-92b1-4a8c-ba8f-7f83aaedd983.png)

**Comment by rustzz** [comment]
in new world skin restored, after morph from mob to character, visual glitch exist

**Comment by iChun** [comment]
As you already know, I no longer support 1.12.2 and older (in which case this version is even further back). 

Due to its age most of the issues I know that were on those versions (and their workaround/solutions) have been lost to time. If it's not stated on the 1.7.10 FAQ here I don't know how else to help, sorry

https://github.com/iChun/Morph/issues/796
