### ISSUE TITLE
Morph Crashing Forge 1.16.5

### ISSUE THREAD

**Issue by Mirixyz** [iChun/Morph#1184]
So I'm using morph and I'm on 1.16.5 Forge I need help to fix it here's the crash report.

The crash report is there so if you could tell me how to fix it.
https://bytebin.lucko.me/INV65PrcHB

**Comment by Ashley123477** [comment]
Also having this crash, forge 36.2.21 1.16.5

**Comment by Ashley123477** [comment]
Seems the moment you turn into any given mob

**Comment by phaniepack** [comment]
same thing happening here, haven't fixed it yet

**Comment by iChun** [comment]
Unfortunately I think the link to the crash log has expired, so I can't debug this crash currently. Fingers crossed it's one of the crashes posted in the other issues and it gets fixed in the next update. Kindly open a new issue if you have a crash log you can contribute, I'll be closing this one for now.
