### ISSUE TITLE
Morph's and Hat's not saving 

### ISSUE THREAD

**Issue by TheRazorBeast** [iChun/Morph#1186]
Hi, First off great mod you made here, absolutely love it :)

I have an issue with the morph mod/hat mod in a modpack and they both don't save leaving my single player world. I'm going to provide as much info as I possibly can. All the mods listed below aren't exactly updated to latest version.

Version: 1.7.10 (I know you don't support this version anymore but I'd appreciate if you take the time to look into it)

Other mods in Modpack:
DamageIndicatorsMod
LuckyBlockV5
Advent-of-Ascension
Animated-Player-Mod
AnimationAPI
ArcanaRPG
Backpack
BackTools
CodeChickenCore
CustomPets
Decocraft
Dungeonpack
DynamicLights
Elemental-Witch-Mod
EnchantingPlus
Extra-Golems-Mod
ExtremeFarming_Mod
FamiliarsAPI
FamiliarsDefaultMobPack
FamiliarsExtendedFamPack
FamiliarsHerobrineFamPack
Flesh2lether
Grim3212-Core
Hats-4.0.1
Headcrumbs
iChunUtil
InfernalMobs
LootsBags-Mod
Malisiscore
Malisisdoors
Mine-Blade-Battlegear-2-mod
MobAmputation
MobDismembrement
Morph-Beta
MrCrayfishFunitureMod
MutantCreatures
NotEnoughItems
obscore
obstrophies
PandorasBox
Pokeball-Mod-by-grim3212
Ruins
Telepads
Torched
Tree-Capitator-Mod
Youtubers-Mod
Zans-MinimapNoRadar-Mod
VoxelMap

I can attach any config files if needed!
I'm so sorry for bothering you for a mod version you don't support anymore, But if you can offer any advice that might help me out, I'd appreciate it. Sorry for any inconvenience. Again love the work that you do!

**Comment by iChun** [comment]
I'm not too sure that I can provide any feedback, as you already know, I no longer support 1.12.2 and older (in which case this version is even further back). 

Due to its age most of the issues I know that were on those versions (and their workaround/solutions) have been lost to time. If it's not stated on the 1.7.10 FAQ here I don't know how else to help, sorry

https://github.com/iChun/Morph/issues/796
