### ISSUE TITLE
Morph crashing when pressing the favourites key

### ISSUE THREAD

**Issue by booskahmed** [iChun/Morph#1187]
There is no option to configure morph keybinds in the ingame controls menu. The only option showing up is  "Favorites" key. When i press it, the client crashes, but not the server.

I'm playing on the Ragnamod VI modpack ([modlist](https://www.modpackindex.com/modpack/35313/ragnamod-vi)) and added morph to it

Here's the crash report :
[crash-2022-02-27_21.02.15-client.txt](https://github.com/iChun/Morph/files/8149384/crash-2022-02-27_21.02.15-client.txt)

**Comment by iChun** [comment]
Are you using a custom key bind manager? Some of Morph's keybinds are a
little special but they show up normally in the vanilla keybinds list and
can be rebound.

**Comment by iChun** [comment]
![image](https://user-images.githubusercontent.com/2298444/157145088-975d9007-2140-4f64-8360-257124c16a56.png)

Going through the issues, and double checked the keybinds thing.

I also investigated your crash, and it seems to be crashing due to a non-set name in a GameProfile on Botania's side. Morph uses iChunUtil to pull the full game profile details using a UUID, from Mojang's servers. Are you playing offline or unauthenticated?

**Comment by iChun** [comment]
Crash will be fixed in the next update.
