### ISSUE TITLE
I cant fly in the new 1.16.5 version of the morph mod

### ISSUE THREAD

**Issue by UnimitedPixel** [iChun/Morph#1208]
Hey iChun, I was play Minecraft with the new rewritten version of the morph mod and I doesn't have any flight icons or any indications that a mob can fly etc. And I can only do like a jump type fly with certain mobs but it doesn't work with mobs like blaze, wither, the ender dragon and other mods and I was wondering if it was a bug a glitch or something else because I was able to fly with the blaze before like  actually flying but that was it and I was wondering if someone could give me and answer or a solution

**Comment by iChun** [comment]
Hiya, the icons are gone now as they are pending an artist to supply new icons as well as the development of biomass to become the default mode for the mod. There will be a way to figure out what mobs have what abilities or traits later down the line.

Mobs without wings that can fly like the blaze and wither use creative-type flight. If you can't seem to toggle it on, it might be because there is a mod conflict due to another mod enabling creative flight using their own content eg rings/armor of flight. Best you try using an instance with just Morph (and iChunUtil) installed to see if that is the case.

**Comment by UnimitedPixel** [comment]
Okay ill try that thanks
