### ISSUE TITLE
Minecraft Morph and Ichun problem 1.7.10 

### ISSUE THREAD

**Issue by stanic11060** [iChun/Morph#1226]
So i am playing a lotr mod with lotr map. The point is, everything is working normal, until i added morph mod and ichun. In first i thought the problem was i didn't have latest versions of mods but i tryed that to. I downloaded every single version of the mod and i kept getting the same mistake. This is the problem. Please help me i am really desperate in trying to fix this. 
https://imgur.com/a/lH6FnP6
This is my discord name if you can help me ipce#1399 or write here. Thanks <3

**Comment by iChun** [comment]
MC 1.7.10 is no longer supported. Sorry.

Obligatory: https://howoldisminecraft1710.today/

Also: https://github.com/iChun/Morph/issues/878

**Comment by stanic11060** [comment]
> 

So you telling me that i can't use morph mod on 1.7.10 version of minecraft. My whole mod pack is on 1.7.10 so i can't go to other version.

**Comment by iChun** [comment]
Morph and iChunUtil on its own works fine last I checked, there were a lot of mod-related incompatibilities in the past.

However, the source code for Morph 1.7.10 is still available on this repo and if you want you can try to track down the issue and fix up the code, if the issue lies on Morph's end.
