### ISSUE TITLE
Farlander invalid morph pig

### ISSUE THREAD

**Issue by Natedogwoooof** [iChun/Morph#1231]
the farlander morph from farlanders is invaild is there a fix to this?

**Comment by Natedogwoooof** [comment]
Also elder farlanders are invalid and can you give the lettice chicken from chaos awakens slow falL
and birds from chaos awakens cant fly.

**Comment by Natedogwoooof** [comment]
classic enderman is also invalid these are all from the same mod

**Comment by iChun** [comment]
![image](https://user-images.githubusercontent.com/2298444/212427948-795f19b5-eaed-41fa-b540-9d86736794f7.png)

There's an error when creating the mob on the client. Will need to be fixed by the affected mod.

RE: no abilities
![image](https://user-images.githubusercontent.com/2298444/212428057-76a1176e-9add-408d-afd0-510b158b827f.png)
