### ISSUE TITLE
[Bug]: inability to fly when using morph, together with GraviSuite

### ISSUE THREAD

**Issue by KempeR0744** [iChun/Morph#1262]
Hello everyone! I recently encountered one problem, playing with friends on the network, when using the mod "Morph" together with "GraviSuite" for version 1.7.10. So, what is the point: when using gravity vest (not including gravity engine) flight on mobs works like Bat and Visp) Everything is normal, all good. but when you turn on the gravity engine, on the server client (the one who opened the world for the network) not work flight. when you want to take off, it immediately "crash" (drop, impasibility of flight). in general some kind of bug.
Help me please solve this bug!

**Comment by Natedogwoooof** [comment]
1.7.10 is unsupported BUT maybe you can see it if dose the same on singleplayer.

**Comment by KempeR0744** [comment]
Who told you that it is not supported? It is quite a popular mod among projects in the Russian-speaking regions. (gravisuite)

**Comment by iChun** [comment]
> Who told you that it is not supported? It is quite a popular mod among projects in the Russian-speaking regions. (gravisuite)

https://github.com/iChun/Morph/issues/878

Obligatory: https://howoldisminecraft1710.today/

Flight not working on these old versions of Morph is usually due to a mod conflict: There is no mod-compatible way to toggle the creative flight allowed flag on players, when multiple mods try to set it to true/false in different circumstances, that leads to mods errornously disabling/enabling flight on the player. 

Support for 1.7.10 was stopped ages ago due to the age of the mod and this issue will not be fixed.

**Comment by KempeR0744** [comment]
i understand
