### ISSUE TITLE
Hard code health as a modifier for certian morphs

### ISSUE THREAD

**Issue by Alex-the-666** [iChun/Morph#715]
some mods, particularly Fossils and Archeology Revival(https://github.com/FossilsArcheologyRevival/FossilArcheology1.7), which have dynamic health systems for their mobs, have problems with Morph health systems. I am requesting a way to hard code a health level(similar to how the attributes are done).

**Comment by iChun** [comment]
Morph's health system is indeed using the attributes system. The problem
here is that it's defaulting to the mob's default health when the mob
instance is created, so that is used instead. I'll try and see what I can
do about this in the future.

**Comment by Alex-the-666** [comment]
Maybe health can be an ability that can be assigned, but if it is null then it uses the default value.

**Comment by iChun** [comment]
Morph 1.12.2 already has code to fix this when it gets it's health balancing feature back.

This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
