### ISSUE TITLE
Multiple flight-unlock mobs?

### ISSUE THREAD

**Issue by Zsashas** [iChun/Morph#770]
Is it possible to require killing more than one custom mob to unlock flight? For example, the four Outer Lands bosses from Thaumcraft, or a few of the Ars Magica guardians.

**Comment by iChun** [comment]
At the moment, no, sorry! It was done as a quick config option for people
requesting a way to unlock it.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.

**Comment by Zsashas** [comment]
Perhaps this could be included as an option for 1.12?

**Comment by iChun** [comment]
When flight comes back I don't quite know how it'll be implemented yet so
for now I don't wanna say how it'll be done.

On 15 Nov 2017 3:13 pm, "Zsashas" <notifications@github.com> wrote:

Perhaps this could be included as an option for 1.12?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/iChun/Morph/issues/770#issuecomment-344505893>, or mute
the thread
