### ISSUE TITLE
Lack of Grimoire of Gaia 3 abilities

### ISSUE THREAD

**Issue by mathwizi2005** [iChun/Morph#802]
After a standardization code cleanup on [GoG](http://www.minecraftforum.net/topic/1355291), all abilities Morph was grabbing dissappeared. I am noting that with GoG 1.2.7 and Morph 0.9.2, even tho Abilitysupport.json lists all GoG mobs and there respective abilities, the ingame effect has none.
[Screen](http://puu.sh/nh0w9/b8f9742c93.png)

**Comment by iChun** [comment]
Just an FYI if they changed their entity class path, AbilitySupport needs to be updated to reflect those changes.

===============================

This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
