### ISSUE TITLE
Mo Creatures and Morph Don't Work

### ISSUE THREAD

**Issue by Starlightwhisper2109** [iChun/Morph#844]
So I have both mods installed, along with a few others. Minecraft works ok with the mods. I play in creative most of the time, so I can access nearly any morph.... But when I look for mo' creatures mobs, they aren't there, only the vanilla are. Minecraft version is 1.10.2, the launcher I use is MultiMC. Any ideas on what could be wrong?

Also, while we're on the topic of morphs, is it possible to morph into other types of mobs... Like the ocelot, is it possible in 1.10.2 to morph into the default tuxedo cat or Siamese or ginger tabby?

**Comment by Tamaized** [comment]
If the Entity doesn't extend EntityLivingBase in code then they wont work along side Morph.

**Comment by Starlightwhisper2109** [comment]
What do you mean by "in code"? I went into the config file for both mods and it didn't say anything about EntityLivingBase... 

And yes, minecraft version 1.10.2

**Comment by Tamaized** [comment]
Not sure how you got your hands on a 1.10.2 version of Morph, most likely isnt an official one. As for in code, I quite literally mean the actual code of the mod, it depends on how the Author wrote his code that depends if it's compatible or not.

**Comment by iChun** [comment]
I think you might have been using MetaMorph. That mod is similar to but not the same as Morph. Different authors and very very different code.

This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
