### ISSUE TITLE
Metamorh 1.10.2: Will mobs still attack you?

### ISSUE THREAD

**Issue by XxDonavinxX** [iChun/Morph#849]
I wanna know if the hostile mobs will still attack me if I'm morphed as that same mob and/or a different mob. If so, then is there a way I can stop that? I checked the config file and there's nothing about mob hostility.

**Comment by iChun** [comment]
Metamorph isn't my mod...

**Comment by XxDonavinxX** [comment]
but isn't that the name of the 1.10.2 version of the morph mod? it said that when i downloaded it

**Comment by iChun** [comment]
.... No. The 1.10.2 version of Morph would be called Morph. Metamorph is a
mod inspired by Morph that is actually written by a different author and
available for 1.10.2.

On 10 Jun 2017 4:32 am, "XxDonavinxX" <notifications@github.com> wrote:

but isn't that the name of the 1.10.2 version of the morph mod? it said
that when i downloaded it

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iChun/Morph/issues/849#issuecomment-307492547>, or mute
the thread

**Comment by XxDonavinxX** [comment]
oh ok. i'll close this.
