### ISSUE TITLE
Hostile morphs attack the player in survival. [1.12.2]

### ISSUE THREAD

**Issue by 63502** [iChun/Morph#881]
For some reason, when I am morphed into a hostile mob, after a short period of time, I will start taking damage as though the mob I am morphed into is attacking me. If I die to this damage, my death message will say I was killed by the mob I was morphed into. There are no crashes involved.

[Mod List](https://gist.github.com/63502/a7cc470cc703b22f597a99c672734582)

**Comment by iChun** [comment]
Oh huh. I'll see if I can address this... Your morphs shouldn't have AI to
try and attack you though :/

On 14 Nov 2017 3:42 am, "63502" <notifications@github.com> wrote:

For some reason, when I am morphed into a hostile mob, after a short period
of time, I will start taking damage as though the mob I am morphed into is
attacking me. If I die to this damage, my death message will say I was
killed by the mob I was morphed into. There are no crashes involved.

Mod List <https://gist.github.com/63502/a7cc470cc703b22f597a99c672734582>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iChun/Morph/issues/881>, or mute the thread

**Comment by 63502** [comment]
Yeah... I kinda guessed that something was wonky when I started punching myself in the face for no reason whenever I morphed into a spider. :P 

I do have one other random question related to spiders, squids, and such. Will mob abilities/attributes be arriving at a later date? I noticed they weren't in when I went swimming as a squid and ended up drowning.

**Comment by iChun** [comment]
Yes. They're not in at the moment because I have no time to reimplement them.
