### ISSUE TITLE
Problems with Animinia and Chickens Mod

### ISSUE THREAD

**Issue by Preminenc3** [iChun/Morph#893]
For the Animania mod it doesn't "stack" the animals, as in they are not vertical to each other and instead horizontal as if it's a different mob, and also the baby Animania animals you can get there morph but nothing shows up and the morph icon is blank, and when you morph into them nothing shows.

For the Chickens mod (Adds ingot chickens etc...) the chickens don't stack so they are all horizontal when you look to morph, instead of there only being one chicken and then you go vertical.

**Comment by iChun** [comment]
Their NBT tags makes Morph think they're different mobs. If you know the tags that make them different you can contribute to the NBT modifier that Morph uses.

https://github.com/iChun/Morph/blob/1.12.2/src/main/resources/assets/morph/mod/nbt_modifiers.json

**Comment by GenDeathrow** [comment]
@iChun I'm helping maintain the chickens mod, Since Setycz is taking a break. 

Question on best way to handle this. 
`  "com.setycz.chickens.entity.EntityChickensChicken": {
	"Type": "null",
	"Strength": "null",
	"Growth": "null",
	"Gain": "null",
	"Analyzed": "null"
  },
`
"Type" determines what chicken it is (needed for rendering), do I just omit that line? or leave it as is. This is all the nbt data thats saved. Also they extend off chickens, So Do I also need to add the same nbt stuff that you have for chickens or is that already handled?

Thanks for taking the time to read.

**Comment by iChun** [comment]
@GenDeathrow the stuff for chickens is already handled. NBT Modifiers are recursive. Did you read the documentation at the top of the file though? https://github.com/iChun/Morph/blob/1.12.2/src/main/resources/assets/morph/mod/nbt_modifiers.json

If Type is what determines how they look, it should be omitted from the modifier. The modifier is just to equalise NBT Tags that are not important to how the mob appears.

**Comment by iChun** [comment]
The chicken lines: https://github.com/iChun/Morph/blob/1.12.2/src/main/resources/assets/morph/mod/nbt_modifiers.json#L107

EntityLivingBase lines: https://github.com/iChun/Morph/blob/1.12.2/src/main/resources/assets/morph/mod/nbt_modifiers.json#L33

using /morph analyse <player> <entity name> would help see how Morph handles the tags.

**Comment by GenDeathrow** [comment]
Yeah I had read it, but was only confused by, If I actually needed to handle the "Type" or not (since its needed for rendering and naming. I didn't want o mess that part up). I'm on holiday vacation so I don't really have a chance to test/code anything. But I will check the /morph analyse when I get back. Thanks for getting back to me quick.

**Comment by iChun** [comment]
Nah you don't have to modify or remove any NBT tags if they're used for
appearance. If you remove type the player would be constantly getting the
same Morph of type 0 if you have a chicken of that type.

**Comment by capnkirok** [comment]
o/ @iChun 

Have been asked to add Animania chicken support to Morph (via a cross-post). Will read your documentation first though :)
