### ISSUE TITLE
incompatibility with lucraftcore mod

### ISSUE THREAD

**Issue by JoeSGT** [iChun/Morph#901]
hello,
the current version i am running is 
ichunutil - 7.1.2     
morph - 7.1.0   
lucraftcore - 1.12-1.2.3 

i just morph into something example a pig and i crash
here is the crash report https://pastebin.com/dhVWW6Vg

**Comment by iChun** [comment]
I can't help you if you don't give me more details, logs, information, etc

**Comment by iChun** [comment]
Oh wait nvm.

**Comment by iChun** [comment]
Can you send this log over to them?

**Comment by JoeSGT** [comment]
I did but no replys

**Comment by iChun** [comment]
They core mod so it's most likely something to fix on their end unless I know what's causing the crash on their end and can try fixing it.

When did you notify them?

**Comment by JoeSGT** [comment]
Yesterday around 2:00 pm EST time zone
they were online but they didn't reply

**Comment by iChun** [comment]
Give them some time, they might not have seen it or might not have checked
the issues.

On 28 Nov 2017 3:58 pm, "JoeSGT" <notifications@github.com> wrote:

Yesterday around 2:00 pm EST time zone
they were online but they didn't reply

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iChun/Morph/issues/901#issuecomment-347442686>, or mute
the thread

**Comment by JoeSGT** [comment]
Alright i will

**Comment by iChun** [comment]
I'm gonna close this cause I think this is a lucraft mod issue, but if they get back to you saying it's Morph's, let me know.
