### ISSUE TITLE
New morph for every mob killed on EU2 Cursed Earth

### ISSUE THREAD

**Issue by therodet** [iChun/Morph#905]
Killing mobs on a Extra Utilities 2 Cursed Earth mob spawner; Every mob is giving a new morph. I'm guessing this is because the cursed earth spawned mobs have a Time-To-Live attribute that is different every time.

**Comment by iChun** [comment]
You could add it to the NBT modifier to reduce the duplicates. Just submit
a pull request. It's in the 1.12.2 branch.

On 8 Dec 2017 2:31 AM, "therodet" <notifications@github.com> wrote:

Killing mobs on a Extra Utilities 2 Cursed Earth mob spawner; Every mob is
giving a new morph. I'm guessing this is because the cursed earth spawned
mobs have a Time-To-Live attribute that is different every time.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iChun/Morph/issues/905>, or mute the thread

**Comment by iChun** [comment]
https://github.com/iChun/Morph/blob/1.12.2/src/main/resources/assets/morph/mod/nbt_modifiers.json
