### ISSUE TITLE
Unable to morph

### ISSUE THREAD

**Issue by Mugiwaxar** [iChun/Morph#980]
Hello
After 50+ hours of playing, any meteorite have crashed on my world
Are they a way to bypass the need of that?

Game version: 1.12.2
Mod pack: FTB Revelation
Morph version: 7.1.2

**Comment by iChun** [comment]
The meteorite doesn't exist in the mod. What issues are you having being
unable to morph?

**Comment by HyperMan19680** [comment]
I’ll say you are. NEVER download mods from sites like 9Minecraft.com<http://9Minecraft.com>. They hide mods behind paywalls that never make it to their creator’s wallets.

On Aug 30, 2018, at 7:22 AM, Mugiwaxar <notifications@github.com<mailto:notifications@github.com>> wrote:


Wait, what?
http://www.9minecraft.net/morphing-mod/<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.9minecraft.net%2Fmorphing-mod%2F&data=02%7C01%7C%7C9130ccadf4a646ddaae808d60e733f62%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636712285473939484&sdata=VrJegGrYz25af8Oed2qNTq19uUeyQgpZrDlFh1K5HgI%3D&reserved=0>
Am I using the wrong mod?

**Comment by Mugiwaxar** [comment]
Don't worry, I download all my mods from curse or gitub.
I just used this site for more explanation about morph, and it talk about a meteorite

**Comment by Theagle43** [comment]
The answer you're looking for, I believe:
Use the [ or ] key to bring up the list of acquired morphs, and to cycle through them. Once you find the one you want, press "Enter". This will morph you into the mob.
To make things quicker, you can press the "~" key instead of "Enter" once you've cycled to a mob to "Favorite" it. Then, later, you can hold down "~" to bring up the Favorites wheel and choose your morph with your mouse.

**Comment by iChun** [comment]
That's in reference to this.
https://www.reddit.com/r/feedthebeast/comments/1vhu4i/morphs_future_plans_in_detail/

Note the date on it. It hasn't been implemented due to other issues.
